apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-ui
  labels:
    app: dashboard-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-ui
  template:
    metadata:
      labels:
        app: dashboard-ui
    spec:
      containers:
        - name: dashboard-ui
          image: dashboard-ui:dev
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
