apiVersion: v1
kind: Service
metadata:
  name: dashboard-ui
  labels:
    app: dashboard-ui
spec:
  type: ClusterIP
  selector:
    app: dashboard-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
